version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - enhancement
  - dependency-update
  ignore:
  - dependency-name: com.diffplug.spotless
    versions:
    - 5.10.1
    - 5.12.0
  - dependency-name: org.sonarqube
    versions:
    - 3.1.1
