language: java
jdk:
  - oraclejdk8
  - openjdk8

script:
  - ./gradlew build
addons:
  sonarcloud:
    organization: "fr1zle-github"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
