language: java
jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "fr1zle-github"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
  - ./gradlew sonarqube
